# -*- coding: utf-8 -*-
"""forestFirePredictionUsing_RandomForestRegressor_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmAxey8eP3C9UFAxVGXlFsiGhyMc8924
"""

import pandas as panda
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import StandardScaler as ss
from sklearn.ensemble import RandomForestRegressor as rfr
from sklearn.metrics import mean_squared_error as mse, r2_score as r2

file_path = '/content/forestfires.csv'
fire = panda.read_csv(file_path)

print(fire.head())

fire_encode = panda.get_dummies(fire, columns=['month', 'day'])

X = fire_encode.drop(['area'], axis=1)
y = np.log1p(fire_encode['area'])
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, random_state=42)

scaler = ss()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(rfr(random_state=42), param_grid, cv=3, n_jobs=-1, scoring='r2')
grid_search.fit(X_train_scaled, y_train)

print("Best parameters found: ", grid_search.best_params_)

best_model = grid_search.best_estimator_

y_train_pred = best_model.predict(X_train_scaled)
y_test_pred = best_model.predict(X_test_scaled)

train_mse = mse(y_train, y_train_pred)
test_mse = mse(y_test, y_test_pred)
train_r2 = r2(y_train, y_train_pred)
test_r2 = r2(y_test, y_test_pred)

print(f"Training Mean Squared Error (MSE): {train_mse}")
print(f"Testing Mean Squared Error (MSE): {test_mse}")
print(f"Training R-squared (R²): {train_r2}")
print(f"Testing R-squared (R²): {test_r2}")